### PR TITLE
[WIP][13.0][MIG] stock_product_pack

### PR DESCRIPTION
**Pull request by jjscarafia**
This PR needs this one to be merged before: https://github.com/OCA/product-pack/pull/23

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by ernestotejeda** [comment]
Thanks @jjscarafia . Could you check Travis CI ? 
```
  File "/home/travis/build/OCA/product-pack/stock_product_pack/tests/test_stock_product_pack.py", line 131, in test_compute_quantities_dict
    self.assertEqual(self.pack_dc.qty_available, 5)
AssertionError: 0.0 != 5
```

**Comment by jjscarafia** [comment]
thanks @ernestotejeda 
I still didn't found time to fix it, I've try to find the origin of the error but couldn't find it yet. Will invest more time on this weekend. Thanks!

**Comment by jjscarafia** [comment]
close in favor of https://github.com/OCA/product-pack/pull/29

**Pull request closed without merging**
