### PR TITLE
[FIX] sale_product_pack: don't relay on demo data

### PR DESCRIPTION
**Pull request by chienandalu**
In CIs with default localizations we could get a pricelist with an
unexpected currency

cc @Tecnativa TT25413

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The text doesn't seems correct.

**Comment by chienandalu** [comment]
What do you mean?

**Comment by pedrobaeza** [comment]
Previously there was no pricelist modifications :smile:

**Review by pedrobaeza — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]

**Pull request merged**
