### PR TITLE
[15.0][MIG] stock_product_pack: Migration to 15.0 

### PR DESCRIPTION
**Pull request by SiesslPhillip**
Changed Setup Method to no longer copy component 1
(-> due to issues with the copy in combination with a change of the product type and missing parent_id)
please check for validity

### CODE REVIEW

**Review by ernesto-garcia-tecnativa — APPROVED** [review]

**Review by ernesto-garcia-tecnativa — APPROVED** [review]
Code review OK
Functional review OK

**Comment by pedrobaeza** [comment]
/ocabot migration stock_product_pack

@SiesslPhillip please squash all your migration commits together

**Comment by rven** [comment]
Please squash the **[MIG] stock_product_pack: Migration to 15.0** commits

**Comment by SiesslPhillip** [comment]
@rven @pedrobaeza  im sorry for the inconvenience but wouldnt it be possible to just squash the pr on merge ?

**Comment by pedrobaeza** [comment]
It can't be done on merge. Please check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by rven** [comment]
@SiesslPhillip Why did you close this PR?

**Pull request closed without merging**
