### PR TITLE
[14.0][ADD] pos_product_pack

### PR DESCRIPTION
**Pull request by rousseldenis**
-  [x] Take into account pack lines quantities (1 for now). Added in ROADMAP

### CODE REVIEW

**Comment by rousseldenis** [comment]
Still applicable

**Review by baimont — APPROVED** [review]
code review, thanks @rousseldenis

**Review by FrancoMaxime — APPROVED** [review]
Reviewed, thanks @rousseldenis

**Review by apineux — APPROVED** [review]

**Comment by rousseldenis** [comment]
@apineux Is this ready ?

**Comment by Bilbonet** [comment]
Hi @rousseldenis 

I find this module very useful.
It's a shame that it's not merged into the repo.

I've been doing tests with the module and I have an issue.
In the POS always shows the pack detailed with the price of the pack and the prices of the products that belongs to it.
Regardless the options you set in the product form.

Maybe if you are still interested in carry on with your work, I'll do test and reviews that can help to finally merge the module.

Thanks in advance for your work and attention.

**Comment by rousseldenis** [comment]
@Bilbonet Thanks. We will merge this and then, improvements could be done with further PR's

**Pull request merged**
