### PR TITLE
[FIX] stock_product_pack: stock on services packs

### PR DESCRIPTION
**Pull request by bruno-zanotti**
In v13 Odoo sets the stock at zero for products that are not services.
This commit will keep the stock of the services if they are packs,
to remain the functionality of the lasts versions.

### CODE REVIEW

**Review by nicomacr — APPROVED** [review]
LGTM

**Review by chienandalu — COMMENTED** [review]
A test would be welcome to avoid future regressions

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Cherry-pick for v14 at c033d13ed613f49f0270eee4ea9e2ee1d140e4b9

**Pull request merged**
