### PR TITLE
[IMP] stock_product_pack: Be able for stock manager to modify packs lines.

### PR DESCRIPTION
**Pull request by nicomacr**
It seems to me that it would be if a user has the maximum stock permission, can edit the lines of packs, as well as a maximum sales permission.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@nicomacr Please check pre-commit

**Comment by nicomacr** [comment]
@rousseldenis Done!

**Review by rousseldenis — APPROVED** [review]

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Pull request merged**
