### PR TITLE
[16.0][FIX] sale_product_pack: Respect the order of the lines to be added

### PR DESCRIPTION
**Pull request by victoralmau**
Respect the order of the lines to be added

**Before**
antes

**After**
despues

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT51380

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
We are losing here a lot of performance, as this applies to all sales order lines, no matter if with pack or not.

Aren't there any other option for this?

**Comment by victoralmau** [comment]
> We are losing here a lot of performance, as this applies to all sales order lines, no matter if with pack or not.
> 
> Aren't there any other option for this?

Changed so that it only applies when any line that is created is a pack.

**Comment by pedrobaeza** [comment]
But it still has the problem with large orders containing packs. You have to find another alternative. How it was done in previous versions? What is the difference now?

**Comment by victoralmau** [comment]
v15 code: https://github.com/OCA/product-pack/blob/15.0/sale_product_pack/models/sale_order_line.py#L79
After creating each of the lines, the extra lines of the pack were auto-created (if applicable).

**Comment by victoralmau** [comment]
Ping @pedrobaeza

**Comment by pedrobaeza** [comment]
Why don't you try to incorporate the pack lines to the dictionary vals list after each record, and call super with all of them, and then only returning those recordsets that are not pack lines? Do you understand me?

**Comment by victoralmau** [comment]
> Why don't you try to incorporate the pack lines to the dictionary vals list after each record, and call super with all of them, and then only returning those recordsets that are not pack lines? Do you understand me?

Yes, I understand what you are saying but “_it is not possible_”. It would be to add to the dictionary the “_extra lines_” that are set in https://github.com/OCA/product-pack/blob/16.0/sale_product_pack/models/sale_order_line.py#L56 but those values are obtained precisely by taking as reference the “_parent_” line (`sale.order.line`) already existing https://github.com/OCA/product-pack/blob/16.0/sale_product_pack/models/product_pack_line.py#L14.

**Review by pedrobaeza — APPROVED** [review]
OK if there's no other solution then.

/ocabot merge patch

**Pull request merged**
