### PR TITLE
[FIX] product_pack: args in _get_product_price/s methods

### PR DESCRIPTION
**Pull request by mav-adhoc**
The arguments of the methods '_get_product_price/s' changed on product_pricelist on native odoo from (self, product, quantity, uom=None, date=False, **kwargs) to (self, product, *args, **kwargs).

### CODE REVIEW

**Comment by mav-adhoc** [comment]
Hi @ernestotejeda, Could you do the reiew plase? Thanks!

**Comment by mav-adhoc** [comment]
@pedrobaeza Could you review this PR? Thanks!

**Comment by pedrobaeza** [comment]
Commit message format is not correct: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

**Comment by pedrobaeza** [comment]
Please put a reference in both the PR and the commit message (in expanded description) to the absolute link to the declaration of such signature.

**Pull request closed without merging**
