### PR TITLE
[FIX] stock_product_pack: Only use stockable products to calculate th…

### PR DESCRIPTION
**Pull request by azucenatrey**
…e stock.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the patch. Seems correct. Please squash both commits into the first.

**Comment by azucenatrey** [comment]
@pedrobaeza, I do not know if I have done the squash correctly.

**Comment by pedrobaeza** [comment]
I'm afraid not. Now there are 6 commits with extra unrelated things!

See https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests for a guide, but you should return to previous state first.

**Comment by ernestotejeda** [comment]
The fix is :+1: for me.
squash correctly for me to approve

**Comment by azucenatrey** [comment]
Sorry but I have not been able to squash correctly, so I have opened a new PR with a single commit:

https://github.com/OCA/product-pack/pull/18

I close this one.

**Pull request closed without merging**
