### PR TITLE
[16.0] [MIG] product_pack: Migration to 16.0

### PR DESCRIPTION
**Pull request by FrancoMaxime**
This pull request is based on the closed pull request (https://github.com/OCA/product-pack/pull/102).

### CODE REVIEW

**Review by baimont — APPROVED** [review]
Technical review, LGTM

**Comment by baimont** [comment]
Functional test: the pack products group could be improved

image

**Comment by FrancoMaxime** [comment]
The view is now fixed

**Review by sanrav — APPROVED** [review]
Functional testing OK

**Pull request merged**
