### PR TITLE
[14.0][MIG] sale_product_pack

### PR DESCRIPTION
**Pull request by mohamedhagag**

### CODE REVIEW

**Comment by jcbr87** [comment]
@mohamedhagag Hello, can I support you in something in this PR?
Thanks

**Comment by mohamedhagag** [comment]
Thanks @jcbr87 for support, appreciated.
I even don't remember what was the problem with the checks, so I don't care anymore.

Regards,

**Comment by pedrobaeza** [comment]
Just rebase. The problem is that the dependency wasn't merged.

**Comment by jcbr87** [comment]
@mohamedhagag If you only do rebase without modifying anything just so that it reruns the checks, with that it is solved. You already have it migrated.
Thanks

**Comment by pedrobaeza** [comment]
I'm afraid you have made a merge instead a rebase. Please do the rebase.

**Comment by mohamedhagag** [comment]
I did a rebase to branch 14.0 from OCA, 
I'm not sure if this is the true way to rebase, sorry if it's not.

**Comment by pedrobaeza** [comment]
See the latest commit that puts "Merge", so something has gone wrong. The steps are:

- git fetch origin 14.0
- git rebase origin/14.0

**Review by jcbr87 — APPROVED** [review]

**Comment by jcbr87** [comment]
@mohamedhagag Hello, sorry for the inconvenience, can you share the module with me in some way, it is that we need it but I see that the process is not progressing in the community.
Thanks

**Review by pere-aquarian — APPROVED** [review]
Code LGTM. Tested in local, working properly. 

Thank you guys fot upgrading, testing and reviewing this module. 
@mohamedhagag

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please rebase instead of doing a merge commit

**Comment by pedrobaeza** [comment]
Superseded by #56

**Pull request closed without merging**
