### PR TITLE
[17.0][MIG] sale_product_pack: Migration to 17.0

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by jappi00** [comment]
Functional: LGTM

**Review by FrancoMaxime — COMMENTED** [review]
Hi @Bruno-Zanotti, Why did you add the migration of product_pack inside this PR instead of using a temporary reference to your other PR? See  [Documentation](https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29)

**Comment by bruno-zanotti** [comment]
@FrancoMaxime because I didn't know about that 😅 let me fix it

**Comment by bruno-zanotti** [comment]
Hey @pedrobaeza @FrancoMaxime, now that product_pack is merged we can merge this one too, same with https://github.com/oca/product-pack/pull/157

**Review by pedrobaeza — APPROVED** [review]

**Review by Abranes — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please rebase and fix pre-commit:

```
sale_product_pack/models/sale_order_line.py:35:89: E501 Line too long (92 > 88)
```

**Pull request merged**
