### PR TITLE
[15.0][MIG] sale_product_pack: Migration to 15.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by nicomacr** [comment]
Pending finish #80

**Comment by jappi00** [comment]
@nicomacr pending pr is done. Do you think you can progress on this in the next time?

**Comment by nicomacr** [comment]
> @nicomacr pending pr is done. Do you think you can progress on this in the next time?
yes I update the status and made the rebase

**Comment by pedrobaeza** [comment]
@nicomacr can you rebase and see if there is any new commit in prior versions?

**Comment by pedrobaeza** [comment]
Sorry, I didn't see that pre-commit was still failing. I have fixed it in #112. You can rebase again and remove your last commit, and let's see if now everything is green.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
