### PR TITLE
[14.0][MIG] stock product pack

### PR DESCRIPTION
**Pull request by jcbr87**

### CODE REVIEW

**Comment by jcbr87** [comment]
@mohamedhagag  Hello, could you help me with a review on this PR?
Thansk

**Comment by jcbr87** [comment]
@peremg can you make a review please?
Thanks

**Review by pere-aquarian — APPROVED** [review]
Code LGTM. Tested in local, working properly.

Thank you guys fot upgrading, testing and reviewing this module.
@jcbr87

**Pull request merged**
