### PR TITLE
[WIP][ADD] sale_product_pack_assisted

### PR DESCRIPTION
**Pull request by jjscarafia**
This PR needs this one to be merged before: https://github.com/OCA/product-pack/pull/24

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Is this abandoned?

**Comment by jjscarafia** [comment]
We're using this on a couple of customers. If someone is interested on this functionality I could ask someone of the team to "improve" the pr

**Comment by jcbr87** [comment]
@jjscarafia Hello, are you still interested in this PR?

**Comment by jjscarafia** [comment]
Hi @jcbr87 
In the past it seem that there was not interest for this module to be merged into OCA, that's why the PR was "abandoned" .
We're still interested on the module and we're actually using it.

If there is interest to include it on OCA we could "improve" the pr.
If there is not interest, we can close the PR (we would keep module on our repos)

Thanks!

**Comment by jcbr87** [comment]
@ jjscarafia Can I help you with something so that it advances and can be mixed?
Thanks

**Pull request closed without merging**
