### PR TITLE
[WIP] Revert "Merge PR #97 into 13.0"

### PR DESCRIPTION
**Pull request by augusto-weiss**
This reverts commit 79bb6e1d0447b59a391e8a567e1d933f1e4680cd, reversing changes made to e06dca7444caa59148876eb96dc7dee0eb180a72.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why?

**Comment by augusto-weiss** [comment]
Hi @pedrobaeza we detect some issues since the merge of that PR (#97)
Also, I noticed that the wrong computation of pack price occurred only with de demo pack, but by creating a new pack we couldn´t replicate the error. 

Two cases that don´t work correctly with PR 97 are:
- Using a pricelist based on another pricelist, with different currencies.
- The discount on sale order line isn´t correctly

We are working on that, so that this PR is WIP on draft

**Comment by pedrobaeza** [comment]
Please start exposing a full steps to reproduce problem, or better, write a unit test that exposes such problem. With that, I can help fixing whatever happens.

**Comment by pedrobaeza** [comment]
Closing as no answer.

**Pull request closed without merging**
