### PR TITLE
[13.0][FIX] website_sale_product_pack: Resilient tests

### PR DESCRIPTION
**Pull request by pedrobaeza**
Create and select a specific pricelist for avoiding problems in integrated environments where the default pricelist currency has been changed.

@Tecnativa

### CODE REVIEW

**Review by cesar-tecnativa — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Not enough, so resetting to draft

**Review by chienandalu — APPROVED** [review]
It was necessary to add the default pricelist to the portal user, which is the one used in the tours. I added the commit with the change, although you can squash it with yours.

**Pull request merged**
