### PR TITLE
[13.0] [FIX] sale_stock_product_pack: avoid error when the cancel quantity for all components.

### PR DESCRIPTION
**Pull request by nicomacr**
In case you cancel the quantity for all components of the pack an error occurred, after this change we set the quantity delivery to zero.

### CODE REVIEW

**Comment by nicomacr** [comment]
@chienandalu could you check this PR?

**Review by jjscarafia — APPROVED** [review]
+1

**Review by chienandalu — APPROVED** [review]

**Comment by nicomacr** [comment]
@pedrobaezai think this PR wasn't merge because is pending an approval (green one) of a maintainer.

**Comment by pedrobaeza** [comment]
There's a problem with the ocabot. @sbidoul is also broken like OCA instance?

**Comment by nicomacr** [comment]
@pedrobaeza it's fixed the problems with ocabot?

**Pull request merged**
