### PR TITLE
[MIG] product_pack: Migration to 17.0

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Review by smcqueen81 — APPROVED** [review]
Functional ok

**Comment by jappi00** [comment]
Functional: LGTM

**Review by FrancoMaxime — APPROVED** [review]
LGTM: code & functional review

**Review by NICO-SOLUTIONS — COMMENTED** [review]
LGTM: Functional review

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Aborted. @gurneyalex please check first the contents before merging, as there's a binary of 30 MB included in this PR: pandoc-3.1.9-1-amd64.deb

**Comment by bruno-zanotti** [comment]
Hey @pedrobaeza @gurneyalex I that binary was added after pre-commit execution (7d81a85769503c54b64435a4c8e7ae05199acef5), not sure why... should I remove it?

**Comment by NICO-SOLUTIONS** [comment]
there are ongoing FIX PR´s for product_pack and website_sale_product_pack. For product_pack its just a small change but i think we should consider it in the migratroin to 17.

**Comment by pedrobaeza** [comment]
Yes, you should remove it. That should be something of pre-commit not cleaning caches.

**Comment by bruno-zanotti** [comment]
@pedrobaeza done!

@NICO-SOLUTIONS if the PRs are still open I think it is better to merge this migration as it is and then when the solution is merge in 16 make the forward port to 17

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
