### PR TITLE
 [14.0][MIG] product_pack

### PR DESCRIPTION
**Pull request by jcbr87**

### CODE REVIEW

**Comment by jcbr87** [comment]
@jaiodoo 
Hello, can you make a review in this migration?

**Comment by jcbr87** [comment]
@pere-aquarian
Hello, can you make a review in this migration?
Thanks

**Comment by jcbr87** [comment]
@rlrawedoo Hello, can you make a review in this migration?
Thanks

**Comment by randy87larosa** [comment]
Hello @jcbr87 , being interested in the migration of this module. I have reviewed this branch and it seems to me that it works
 correctly.

**Comment by jcbr87** [comment]
@pedrobaeza Hello I am interested in mixing this migration, do I need something else?
thanks

**Comment by pedrobaeza** [comment]
There should be qualified reviews. You can review other PRs and ask in exchange to review yours.

**Comment by jaiodoo** [comment]
Hello @jcbr87 , i interested in the migration of this module. I have tested this branch and it seems to me that it correct.

**Comment by jcbr87** [comment]
> There should be qualified reviews. You can review other PRs and ask in exchange to review yours.

**Comment by jcbr87** [comment]
@pedrobaeza I already have two revisions, do we need something else?

**Comment by pedrobaeza** [comment]
No, there isn't any, and one at least should come from a PSC member. You are also not respecting the previous migration done in #33. You should review that one instead of creating a new one.

**Comment by peremg** [comment]
Hi, @pedrobaeza , 

I [asked](https://github.com/mohamedhagag/product-pack/commit/11bfbabb9f970081c292119a0d8b760badfd7ea0#commitcomment-54148173) to @mohamedhagag if he was going to go ahead with the migration (and also if he needs any help). 

Baring this in mind, please tell me if we had to act in other maner. 

Thank you!

**Comment by jcbr87** [comment]
> No, there isn't any, and one at least should come from a PSC member. You are also not respecting the previous migration done in #33. You should review that one instead of creating a new one.

@pedrobaeza 
The owner of PR # 33 has been asked and has commented that he is not interested in following up. And I need that migrated module to be able to migrate the others and use the repository.

**Comment by jcbr87** [comment]
@dreispt Hello, can you validate this PR please.
Thanks

**Comment by jcbr87** [comment]
@ernestotejeda  Hello, can you validate this PR please.
Thanks

**Comment by jcbr87** [comment]
@pedrobaeza 

Hello, I can do something else to advance my PR, I do not know if there is interest in the community about this repository, it seems that not.

**Comment by jcbr87** [comment]
@chienandalu  Hello, can you validate this PR please.
Thanks

**Comment by jcbr87** [comment]
@jjscarafia  Hello, can you validate this PR please.
Thanks

**Comment by chienandalu** [comment]
@jcbr87 I was taking a tour on pendant PRs so nothing is left outside the migration. Please be patient :wink:

**Comment by jcbr87** [comment]
@chienandalu Hello, if there is no problem, with an answer I already know that my PR will eventually arrive, but I have touched other Repositories that months to have a review.

Thanks

**Review by ernestotejeda — COMMENTED** [review]
Code and functional review: OK...but, put the changes of the pre-commit in a separated commit before the migration commit as it is described here https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch.

**Comment by jcbr87** [comment]
@ernestotejeda  Thank you, just as you suggest that the change of the confirmation be done.

**Comment by jcbr87** [comment]
@pedrobaeza Hello, they have already made a review, do we need another?
Thanks

**Comment by pedrobaeza** [comment]
Yes, and you don't deserve a "free" one, as you are only demanding things in a very impatient way without doing a review of other things in exchange. This is not how community works.

**Comment by jcbr87** [comment]
@pedrobaeza 
Hello, an apology first of all, my intention has not been to make you feel impatient, I was just asking you if there was something that was in my hands to advance the process.
Sorry for the inconvenience. Thanks

**Comment by pedrobaeza** [comment]
Why don't you then proves your involvement and review other pull requests?

**Comment by jcbr87** [comment]
Hello @nicomacr , can you support me with a review on this PR?
Thanks

**Review by mohamedhagag — APPROVED** [review]
@jcbr87 
Functional & Technical review:
Everything seems ok & functional .

**Comment by pedrobaeza** [comment]
OK, let's merge as CI is OK and it seems no other changes are needed:

/ocabot merge nobump

**Pull request merged**
